### ISSUE TITLE
Run >+20ML for  MagiMechTech MechaMech Bounty

### ISSUE THREAD

**Issue by Alium58** [loathers/bountiful#19]
The NC will only give the mech when running > +20ML

https://kol.coldfront.net/thekolwiki/index.php/Random_Lack_of_an_Encounter

**Comment by Veracity0** [comment]
I've noticed this myself and have worked around it by casting Ur-Kel's multiple times before starting the hunt. It would be nice if the script would could handle this.

**Comment by Alium58** [comment]
fixed in #29
