### ISSUE TITLE
Shape of...Mole! and Half-Astral are limitmodes

### ISSUE THREAD

**Issue by Veracity0** [loathers/bountiful#25]
1) The llama lama gong bounty (6 pop art banana peels from velvet underground dwellers) sends you to Mt. Molehill.
Once you are in Shape of...Mole!, you are stuck that way for 12 turns.
You cannot adventure anywhere except Mt. Molehill until you exit your adventure in the Welcome Back! choice adventure.
KoLmafia tracks this by setting limit_mode() to "mole".

When bountiful gets the last bounty, it thinks it is done with Mt. Molehill.

For the purpose of collecting lucre, that is true.

However, the character is still stuck in the limitmode.

At that moment, it is up to the player to notice that and do whatever is necessary to exit that state.
If they fail to do that, the next adventure they attempt will send them right back to Mt. Molehill.
That includes, for example, typing "bountiful hunt easy".

I got burned by trying to run another script, which over drank after it thought it was "done" adventuring. Oops.
I fixed that script so it will do nothing if invoked in a limitmode.

Arguably, it was up to me to notice that bountiful left me "stuck" in limitmode=mole.
Arguably, perhaps bountiful should have collected the bounty and then adventured enough to exit the limitmode.

I'm not sure, but I'm bringing it up for you to ponder.

2) The astral mushroom bounty (8 piles of country guano from country bats) behaves the same way for limit_mode() == "astral". You are stuck in An Incredibly Strange Place (Bad Trip) for 5 turns.

**Comment by Alium58** [comment]
Excellent write up, thanks for making this! Also appreciate the other issues you have created. Have a PR in progress to fix many of these issues

**Comment by Alium58** [comment]
Oh I should mention that decision I made was to have bountiful shrug (astral mushroom) or burn turns (mole) to get out of limit mode before completing. Agree it is an unexpected state to end the script in and can easily cause issues

**Comment by Alium58** [comment]
fixed in #29
