### ISSUE TITLE
Improve Combat

### ISSUE THREAD

**Issue by Alium58** [loathers/bountiful#8]
Currently script does sniffing, banishing, copying and then simply attacks. Should improve this to cast spells if attacks do negligible damage

**Comment by Alium58** [comment]
User reported combat particularly bad for SSB bounty as it has scalers

**Comment by Veracity0** [comment]
In the same vein, on Mt. Molehill, I want to Tunnel Down each fight in order to steer to the rewards I want.

I worked around it by adding a CCS entry to do that in that location.

**Comment by Alium58** [comment]
As of #29 Uses spells now. Also tunnels down in mt molehill. Combat isn't perfect, but lots better. Going to close for now, but can reopen if folks are still having combat issues
